### ISSUE TITLE
Alt-Tabbing out and navigating to another app does not count as not visible!

### ISSUE THREAD

**Issue by mfsi-akshay** [jasonzissman/TimeMe.js#23] opened 2016-02-04 20:53 UTC
If a user switches from the browser window by alt-tabbing out, the user is still considered as active. The demo provided also show this behavior!

**Comment by mfsi-akshay** [comment] 2016-02-04 20:58
To add to this, if user switches away from browser by not clicking minimize, and simply clicking on any open application in his task-bar, the user is assumed to be interacting with the page!

**Comment by jasonzissman** [comment] 2017-01-28 00:13
Hi!  Thanks for the issue, and I apologize for abandoning this project for so long.  I have created a new branch (PR: https://github.com/jasonzissman/TimeMe.js/pull/29) on which I cannot reproduce this issue.  I tested locally on Windows 10 - Chrome.  Please let me know if this is still an issue for you on the new branch.

**Comment by jasonzissman** [comment] 2017-01-28 15:02
The PR has been merged into master, and I've updated the demo.  I don't believe this is an issue anymore.  If you can recreate, please send me the details.  Thanks!

**Closed by jasonzissman** 2017-01-28 15:02 UTC
